import JSZip from "jszip";
import { ScenarioData } from "@/types/scenario";

export async function generateExportZip(scenario: ScenarioData): Promise<Blob> {
  const zip = new JSZip();

  // Generate the standalone HTML with embedded CSS and JS
  const html = generateStandaloneHTML(scenario);
  zip.file("index.html", html);

  // Add scenario data as JSON for reference
  zip.file("scenario.json", JSON.stringify(scenario, null, 2));

  // Add a readme file
  zip.file("README.txt", generateReadme(scenario.name));

  // If there's a custom avatar image, add it
  if (scenario.theme.contactAvatar) {
    // Extract base64 data and add as image file
    const avatarData = scenario.theme.contactAvatar;
    if (avatarData.startsWith("data:image")) {
      const [header, base64] = avatarData.split(",");
      const mimeMatch = header.match(/data:(image\/\w+);/);
      const extension = mimeMatch ? mimeMatch[1].split("/")[1] : "png";
      zip.file(`avatar.${extension}`, base64, { base64: true });
    }
  }

  return zip.generateAsync({ type: "blob" });
}

function generateReadme(scenarioName: string): string {
  return `${scenarioName} - Chat Scenario Export
=====================================

This folder contains a self-contained chat scenario that can be embedded in
Articulate Rise, Adobe Captivate, or any authoring tool with an embed code feature.

FILES INCLUDED:
- index.html: The complete interactive chat scenario (open in browser to test)
- scenario.json: Raw scenario data for reference or reimport

HOW TO USE IN ARTICULATE RISE:
1. Upload this entire folder to a web server or cloud storage (e.g., AWS S3, GitHub Pages)
2. In Rise, add a "Multimedia" block and select "Embed Code"
3. Use an iframe to embed: <iframe src="YOUR_URL/index.html" width="100%" height="600"></iframe>

HOW TO USE IN OTHER TOOLS:
- Use the iframe embed method described above
- Or directly open index.html in a browser for standalone use

NOTES:
- The chat is fully self-contained with no external dependencies
- Works offline once loaded
- Responsive design adapts to container size

Generated by Chat Scenario Builder
`;
}

function generateStandaloneHTML(scenario: ScenarioData): string {
  const { theme, messages, variables, rootMessageId, name } = scenario;

  // Start screen text with fallbacks
  const startTitle = theme.startScreenTitle ?? "Ready to Start";
  const startSubtitle = theme.startScreenSubtitle ?? "Begin the conversation";
  const startButtonText = theme.startButtonText ?? "Start";
  const startButtonColor = theme.startButtonColor ?? "214 100% 65%";
  const startButtonTextColor = theme.startButtonTextColor ?? "0 0% 100%";
  const startButtonBorderRadius = theme.startButtonBorderRadius ?? 12;
  const showResetButton = theme.showResetButton ?? true;

  // Escape for safe JSON embedding in script
  const scenarioJSON = JSON.stringify({ messages, variables, rootMessageId, theme });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHTML(name)}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: ${theme.fontFamily};
      font-size: clamp(0.875rem, 1rem, 1.125rem);
      line-height: 1.5;
      background-color: hsl(${theme.chatBackground});
      height: 100vh;
      display: flex;
      flex-direction: column;
    }

    /* Screen reader only utility */
    .sr-only {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    }

    .chat-container {
      display: flex;
      flex-direction: column;
      height: 100%;
      max-width: 37.5rem;
      margin: 0 auto;
      width: 100%;
      background: white;
      box-shadow: 0 0 1.25rem rgba(0,0,0,0.1);
    }

    .chat-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 0.75rem 1rem;
      background: white;
      border-bottom: 1px solid #e5e7eb;
    }

    .avatar {
      width: 2.75rem;
      height: 2.75rem;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 600;
      font-size: 0.875rem;
      background: linear-gradient(135deg, hsl(${theme.senderBubbleColor}), hsl(${theme.senderBubbleColor} / 0.7));
      color: hsl(${theme.senderTextColor});
      flex-shrink: 0;
    }

    .avatar img {
      width: 100%;
      height: 100%;
      border-radius: 50%;
      object-fit: cover;
    }

    .header-info {
      flex: 1;
    }

    .header-name {
      font-weight: 600;
      color: #1f2937;
    }

    .header-status {
      font-size: 0.75rem;
      color: #6b7280;
      display: flex;
      align-items: center;
      gap: 0.375rem;
    }

    .status-dot {
      width: 0.5rem;
      height: 0.5rem;
      border-radius: 50%;
      background: #10b981;
      animation: pulse 2s infinite;
    }

    @keyframes pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.5; }
    }

    .reset-btn {
      padding: 0.5rem 1rem;
      border-radius: 0.75rem;
      border: 1px solid #e5e7eb;
      background: white;
      cursor: pointer;
      font-size: 0.875rem;
      font-weight: 500;
      transition: all 0.2s;
    }

    .reset-btn:hover {
      background: #f3f4f6;
    }

    .reset-btn:focus-visible {
      outline: 2px solid #2563eb;
      outline-offset: 2px;
    }

    .chat-messages {
      flex: 1;
      overflow-y: auto;
      padding: 1rem;
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .message-row {
      display: flex;
      animation: fadeIn 0.3s ease-out;
    }

    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(0.625rem); }
      to { opacity: 1; transform: translateY(0); }
    }

    .message-row.user {
      justify-content: flex-end;
    }

    .message-row.contact {
      justify-content: flex-start;
    }

    .message-avatar {
      width: 2rem;
      height: 2rem;
      border-radius: 50%;
      margin-right: 0.75rem;
      flex-shrink: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 600;
      font-size: 0.6875rem;
      background: linear-gradient(135deg, hsl(${theme.senderBubbleColor}), hsl(${theme.senderBubbleColor} / 0.7));
      color: hsl(${theme.senderTextColor});
    }

    .message-avatar img {
      width: 100%;
      height: 100%;
      border-radius: 50%;
      object-fit: cover;
    }

    .message-bubble {
      max-width: 75%;
      padding: 0.625rem 1rem;
      box-shadow: 0 1px 2px rgba(0,0,0,0.05);
    }

    .message-bubble.contact {
      background: hsl(${theme.receiverBubbleColor});
      color: hsl(${theme.receiverTextColor});
      border-top-left-radius: ${(theme.receiverBorderRadius?.topLeft ?? 4) / 16}rem;
      border-top-right-radius: ${(theme.receiverBorderRadius?.topRight ?? 16) / 16}rem;
      border-bottom-right-radius: ${(theme.receiverBorderRadius?.bottomRight ?? 16) / 16}rem;
      border-bottom-left-radius: ${(theme.receiverBorderRadius?.bottomLeft ?? 16) / 16}rem;
    }

    .message-bubble.user {
      background: hsl(${theme.senderBubbleColor});
      color: hsl(${theme.senderTextColor});
      border-top-left-radius: ${(theme.senderBorderRadius?.topLeft ?? 16) / 16}rem;
      border-top-right-radius: ${(theme.senderBorderRadius?.topRight ?? 4) / 16}rem;
      border-bottom-right-radius: ${(theme.senderBorderRadius?.bottomRight ?? 16) / 16}rem;
      border-bottom-left-radius: ${(theme.senderBorderRadius?.bottomLeft ?? 16) / 16}rem;
    }

    .typing-indicator {
      display: flex;
      align-items: center;
      gap: 0.25rem;
      padding: 0.75rem 1rem;
    }

    .typing-dot {
      width: 0.5rem;
      height: 0.5rem;
      border-radius: 50%;
      background: hsl(${theme.receiverTextColor} / 0.5);
      animation: typingBounce 0.6s infinite;
    }

    .typing-dot:nth-child(2) { animation-delay: 0.15s; }
    .typing-dot:nth-child(3) { animation-delay: 0.3s; }

    @keyframes typingBounce {
      0%, 100% { transform: translateY(0); }
      50% { transform: translateY(-0.25rem); }
    }

    .end-indicator {
      display: flex;
      justify-content: center;
      padding-top: 1rem;
    }

    .end-badge {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.5rem 1rem;
      border-radius: 1.25rem;
      background: rgba(16, 185, 129, 0.15);
      color: #10b981;
      font-size: 0.875rem;
      font-weight: 500;
    }

    .end-badge-dot {
      width: 0.5rem;
      height: 0.5rem;
      border-radius: 50%;
      background: #10b981;
    }

    .response-options {
      border-top: 1px solid #e5e7eb;
      padding: 1rem;
      background: white;
    }

    .options-label {
      font-size: 0.6875rem;
      font-weight: 500;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 0.75rem;
    }

    .options-container {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
    }

    .option-btn {
      padding: 0.5rem 1rem;
      border-radius: 0.75rem;
      border: 1px solid #e5e7eb;
      background: white;
      cursor: pointer;
      font-size: 0.875rem;
      transition: all 0.2s;
    }

    .option-btn:hover {
      background: hsl(${theme.senderBubbleColor});
      color: hsl(${theme.senderTextColor});
      border-color: hsl(${theme.senderBubbleColor});
    }

    .option-btn:focus-visible {
      outline: 2px solid #2563eb;
      outline-offset: 2px;
    }

    .option-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .start-screen {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .start-content {
      text-align: center;
      max-width: 17.5rem;
    }

    .start-icon {
      width: 5rem;
      height: 5rem;
      border-radius: 1.5rem;
      background: #f3f4f6;
      margin: 0 auto 1rem;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .start-icon svg {
      width: 2.5rem;
      height: 2.5rem;
      color: #9ca3af;
    }

    .start-title {
      font-size: 1.125rem;
      font-weight: 600;
      color: #1f2937;
      margin-bottom: 0.5rem;
    }

    .start-text {
      font-size: 0.875rem;
      color: #6b7280;
      margin-bottom: 1.25rem;
    }

    .start-btn {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.625rem 1.25rem;
      border-radius: ${startButtonBorderRadius / 16}rem;
      border: none;
      background: hsl(${startButtonColor});
      color: hsl(${startButtonTextColor});
      font-size: 0.875rem;
      font-weight: 500;
      cursor: pointer;
      box-shadow: 0 0.25rem 0.75rem hsl(${startButtonColor} / 0.25);
      transition: all 0.2s;
    }

    .start-btn:hover {
      transform: translateY(-1px);
      box-shadow: 0 0.375rem 1rem hsl(${startButtonColor} / 0.3);
    }

    .start-btn:focus-visible {
      outline: 2px solid #2563eb;
      outline-offset: 2px;
    }

    .start-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
      transform: none;
    }
  </style>
</head>
<body>
  <div class="chat-container" id="app" role="region" aria-label="Chat conversation"></div>
  <!-- Hidden live region for screen reader announcements -->
  <div aria-live="assertive" aria-atomic="true" class="sr-only" id="status-announcer"></div>

  <script>
    (function() {
      const scenario = ${scenarioJSON};
      const { messages, variables, rootMessageId, theme } = scenario;

      let chatHistory = [];
      let currentMessageId = null;
      let isPlaying = false;
      let isTyping = false;
      let variableState = {};

      // Customizable text
      const startTitle = ${JSON.stringify(startTitle)};
      const startSubtitle = ${JSON.stringify(startSubtitle)};
      const startButtonText = ${JSON.stringify(startButtonText)};
      const showResetButton = ${JSON.stringify(showResetButton)};

      // Initialize variable state from defaults
      Object.values(variables || {}).forEach(v => {
        variableState[v.id] = v.defaultValue;
      });

      function getInitials(name) {
        return name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2);
      }

      function checkCondition(condition) {
        if (!condition) return true;
        return variableState[condition.variableId] === condition.requiredValue;
      }

      function applyVariableAssignment(assignment) {
        if (assignment) {
          variableState[assignment.variableId] = assignment.value;
        }
      }

      function getVisibleOptions(message) {
        if (!message || !message.responseOptions) return [];
        return message.responseOptions.filter(opt => checkCondition(opt.condition));
      }

      // Announce status changes to screen readers
      function announceStatus(message) {
        const announcer = document.getElementById('status-announcer');
        if (announcer) {
          announcer.textContent = '';
          setTimeout(function() { announcer.textContent = message; }, 50);
        }
      }

      // Focus management helper
      function focusElement(selector, fallbackSelector) {
        setTimeout(function() {
          const el = document.querySelector(selector);
          if (el) {
            el.focus();
          } else if (fallbackSelector) {
            const fallback = document.querySelector(fallbackSelector);
            if (fallback) fallback.focus();
          }
        }, 100);
      }

      function escapeForAriaLabel(str) {
        return str.replace(/"/g, '&quot;').replace(/'/g, '&#39;');
      }

      function render() {
        const app = document.getElementById('app');
        const currentMessage = currentMessageId ? messages[currentMessageId] : null;
        const rootMessage = rootMessageId ? messages[rootMessageId] : null;

        const visibleOptions = getVisibleOptions(currentMessage);
        const isEnded = isPlaying && currentMessage && !isTyping &&
          (currentMessage.isEndpoint || visibleOptions.length === 0);
        const isDeadEnd = isPlaying && !currentMessageId && chatHistory.length > 0 && !isTyping;

        // Update aria-label with contact name
        app.setAttribute('aria-label', 'Chat conversation with ' + theme.contactName);

        let html = '';

        // Header
        html += '<header class="chat-header">';
        html += '<div class="avatar" aria-hidden="true">';
        if (theme.contactAvatar) {
          html += '<img src="' + theme.contactAvatar + '" alt="">';
        } else {
          html += getInitials(theme.contactName);
        }
        html += '</div>';
        html += '<div class="header-info">';
        html += '<div class="header-name">' + theme.contactName + '</div>';
        html += '<div class="header-status" aria-live="polite">';
        html += '<span class="status-dot" aria-hidden="true"></span>';
        html += '<span>' + (isPlaying ? 'Active now' : 'Click Start to begin') + '</span>';
        html += '</div></div>';
        if (isPlaying && showResetButton) {
          html += '<button class="reset-btn" onclick="handleReset()" aria-label="Reset conversation">↻ Reset</button>';
        }
        html += '</header>';

        if (!isPlaying) {
          // Start screen
          html += '<main class="start-screen"><div class="start-content">';
          html += '<div class="start-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg></div>';
          html += '<h1 class="start-title">' + (rootMessage ? startTitle : 'No Messages') + '</h1>';
          html += '<p class="start-text">' + (rootMessage ? startSubtitle : 'This scenario has no messages') + '</p>';
          html += '<button class="start-btn" id="start-btn" onclick="handleStart()" aria-label="Start conversation"' + (!rootMessage ? ' disabled aria-disabled="true"' : '') + '>';
          html += '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>';
          html += startButtonText;
          html += '</button></div></main>';
        } else {
          // Messages area with log role for screen readers
          html += '<main class="chat-messages" role="log" aria-live="polite" aria-atomic="false" aria-label="Conversation messages" tabindex="-1" id="messages-area">';
          chatHistory.forEach(function(bubble) {
            const senderName = bubble.isUser ? 'You' : theme.contactName;
            const bubbleContent = bubble.content || 'Empty message';
            const ariaLabel = senderName + ' said: ' + escapeForAriaLabel(bubbleContent);
            
            html += '<div class="message-row ' + (bubble.isUser ? 'user' : 'contact') + '" role="article" aria-label="' + ariaLabel + '">';
            if (!bubble.isUser) {
              html += '<div class="message-avatar" aria-hidden="true">';
              if (theme.contactAvatar) {
                html += '<img src="' + theme.contactAvatar + '" alt="">';
              } else {
                html += getInitials(theme.contactName);
              }
              html += '</div>';
            }
            html += '<div class="message-bubble ' + (bubble.isUser ? 'user' : 'contact') + '">';
            html += bubble.content || '<em style="opacity:0.6">Empty message</em>';
            html += '</div></div>';
          });

          // Typing indicator with screen reader announcement
          if (isTyping) {
            html += '<div class="message-row contact" role="status" aria-label="' + theme.contactName + ' is typing">';
            html += '<div class="message-avatar" aria-hidden="true">';
            if (theme.contactAvatar) {
              html += '<img src="' + theme.contactAvatar + '" alt="">';
            } else {
              html += getInitials(theme.contactName);
            }
            html += '</div>';
            html += '<div class="message-bubble contact"><div class="typing-indicator" aria-hidden="true">';
            html += '<span class="typing-dot"></span>';
            html += '<span class="typing-dot"></span>';
            html += '<span class="typing-dot"></span>';
            html += '</div><span class="sr-only">' + theme.contactName + ' is typing</span></div></div>';
          }

          if (isEnded || isDeadEnd) {
            html += '<div class="end-indicator" role="status"><span class="end-badge">';
            html += '<span class="end-badge-dot" aria-hidden="true"></span>';
            html += isEnded ? 'Conversation Complete' : 'End of Branch';
            html += '</span></div>';
          }
          html += '</main>';

          // Response options (hide while typing)
          if (currentMessage && !currentMessage.isEndpoint && visibleOptions.length > 0 && !isTyping) {
            html += '<nav class="response-options" role="group" aria-label="Response options">';
            html += '<div class="options-label" id="options-label" aria-hidden="true">Choose a response</div>';
            html += '<div class="options-container">';
            visibleOptions.forEach(function(opt, index) {
              const isFirst = index === 0;
              html += '<button class="option-btn" id="option-' + opt.id + '" onclick="handleSelect(\\'' + opt.id + '\\')"' + (!opt.text ? ' disabled aria-disabled="true"' : '') + ' aria-label="Respond: ' + escapeForAriaLabel(opt.text || 'Empty option') + '">';
              html += opt.text || 'Empty option';
              html += '</button>';
            });
            html += '</div></nav>';
          }
        }

        app.innerHTML = html;
      }

      function addContactMessage(messageId, content, callback) {
        isTyping = true;
        announceStatus(theme.contactName + ' is typing');
        render();
        
        setTimeout(function() {
          chatHistory.push({
            id: messageId,
            content: content,
            isUser: false
          });
          isTyping = false;
          announceStatus('New message from ' + theme.contactName);
          if (callback) callback();
          render();
          
          // Focus first option if available, otherwise focus messages area
          focusElement('.option-btn', '#messages-area');
        }, 1000);
      }

      window.handleStart = function() {
        if (!rootMessageId || !messages[rootMessageId]) return;
        
        // Reset variable state
        Object.values(variables || {}).forEach(function(v) {
          variableState[v.id] = v.defaultValue;
        });

        isPlaying = true;
        chatHistory = [];
        currentMessageId = rootMessageId;
        
        announceStatus('Conversation started with ' + theme.contactName);
        
        // Show typing indicator, then message
        addContactMessage(rootMessageId, messages[rootMessageId].content);
      };

      window.handleReset = function() {
        isPlaying = false;
        isTyping = false;
        chatHistory = [];
        currentMessageId = null;
        
        // Reset variable state
        Object.values(variables || {}).forEach(function(v) {
          variableState[v.id] = v.defaultValue;
        });
        
        announceStatus('Conversation reset');
        render();
        
        // Focus start button after reset
        focusElement('#start-btn');
      };

      window.handleSelect = function(optionId) {
        const currentMessage = messages[currentMessageId];
        if (!currentMessage) return;

        const option = currentMessage.responseOptions.find(function(o) { return o.id === optionId; });
        if (!option) return;

        // Apply variable assignment
        applyVariableAssignment(option.setsVariable);

        // Add user response immediately
        chatHistory.push({
          id: 'user-' + optionId,
          content: option.text,
          isUser: true
        });
        announceStatus('You said: ' + option.text);
        render();

        // Add next message with typing indicator if exists
        if (option.nextMessageId && messages[option.nextMessageId]) {
          const nextMsg = messages[option.nextMessageId];
          // Check if next message meets its condition
          if (checkCondition(nextMsg.condition)) {
            currentMessageId = option.nextMessageId;
            addContactMessage(option.nextMessageId, nextMsg.content);
          } else {
            currentMessageId = null;
            announceStatus('End of conversation branch');
            render();
          }
        } else {
          currentMessageId = null;
          announceStatus('Conversation complete');
          render();
        }
      };

      render();
      
      // Set initial focus to start button
      focusElement('#start-btn');
    })();
  </script>
</body>
</html>`;
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
