import JSZip from "jszip";
import { ScenarioData } from "@/types/scenario";

export async function generateExportZip(scenario: ScenarioData): Promise<Blob> {
  const zip = new JSZip();

  // Generate the standalone HTML with embedded CSS and JS
  const html = generateStandaloneHTML(scenario);
  zip.file("index.html", html);

  // Add scenario data as JSON for reference
  zip.file("scenario.json", JSON.stringify(scenario, null, 2));

  // Add a readme file
  zip.file("README.txt", generateReadme(scenario.name));

  // If there's a custom avatar image, add it
  if (scenario.theme.contactAvatar) {
    // Extract base64 data and add as image file
    const avatarData = scenario.theme.contactAvatar;
    if (avatarData.startsWith("data:image")) {
      const [header, base64] = avatarData.split(",");
      const mimeMatch = header.match(/data:(image\/\w+);/);
      const extension = mimeMatch ? mimeMatch[1].split("/")[1] : "png";
      zip.file(`avatar.${extension}`, base64, { base64: true });
    }
  }

  return zip.generateAsync({ type: "blob" });
}

function generateReadme(scenarioName: string): string {
  return `${scenarioName} - Chat Scenario Export
=====================================

This folder contains a self-contained chat scenario that can be embedded in
Articulate Rise, Adobe Captivate, or any authoring tool with an embed code feature.

FILES INCLUDED:
- index.html: The complete interactive chat scenario (open in browser to test)
- scenario.json: Raw scenario data for reference or reimport

HOW TO USE IN ARTICULATE RISE:
1. Upload this entire folder to a web server or cloud storage (e.g., AWS S3, GitHub Pages)
2. In Rise, add a "Multimedia" block and select "Embed Code"
3. Use an iframe to embed: <iframe src="YOUR_URL/index.html" width="100%" height="600"></iframe>

HOW TO USE IN OTHER TOOLS:
- Use the iframe embed method described above
- Or directly open index.html in a browser for standalone use

NOTES:
- The chat is fully self-contained with no external dependencies
- Works offline once loaded
- Responsive design adapts to container size

Generated by Chat Scenario Builder
`;
}

function generateStandaloneHTML(scenario: ScenarioData): string {
  const { theme, messages, variables, rootMessageId, name } = scenario;

  // Escape for safe JSON embedding in script
  const scenarioJSON = JSON.stringify({ messages, variables, rootMessageId, theme });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHTML(name)}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: ${theme.fontFamily};
      font-size: ${theme.fontSize}px;
      line-height: 1.5;
      background-color: hsl(${theme.chatBackground});
      height: 100vh;
      display: flex;
      flex-direction: column;
    }

    .chat-container {
      display: flex;
      flex-direction: column;
      height: 100%;
      max-width: 600px;
      margin: 0 auto;
      width: 100%;
      background: white;
      box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }

    .chat-header {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 12px 16px;
      background: white;
      border-bottom: 1px solid #e5e7eb;
    }

    .avatar {
      width: 44px;
      height: 44px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 600;
      font-size: 14px;
      background: linear-gradient(135deg, hsl(${theme.senderBubbleColor}), hsl(${theme.senderBubbleColor} / 0.7));
      color: hsl(${theme.senderTextColor});
      flex-shrink: 0;
    }

    .avatar img {
      width: 100%;
      height: 100%;
      border-radius: 50%;
      object-fit: cover;
    }

    .header-info {
      flex: 1;
    }

    .header-name {
      font-weight: 600;
      color: #1f2937;
    }

    .header-status {
      font-size: 12px;
      color: #6b7280;
      display: flex;
      align-items: center;
      gap: 6px;
    }

    .status-dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: #10b981;
      animation: pulse 2s infinite;
    }

    @keyframes pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.5; }
    }

    .reset-btn {
      padding: 8px 16px;
      border-radius: 12px;
      border: 1px solid #e5e7eb;
      background: white;
      cursor: pointer;
      font-size: 14px;
      font-weight: 500;
      transition: all 0.2s;
    }

    .reset-btn:hover {
      background: #f3f4f6;
    }

    .chat-messages {
      flex: 1;
      overflow-y: auto;
      padding: 16px;
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .message-row {
      display: flex;
      animation: fadeIn 0.3s ease-out;
    }

    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(10px); }
      to { opacity: 1; transform: translateY(0); }
    }

    .message-row.user {
      justify-content: flex-end;
    }

    .message-row.contact {
      justify-content: flex-start;
    }

    .message-avatar {
      width: 32px;
      height: 32px;
      border-radius: 50%;
      margin-right: 12px;
      flex-shrink: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 600;
      font-size: 11px;
      background: linear-gradient(135deg, hsl(${theme.senderBubbleColor}), hsl(${theme.senderBubbleColor} / 0.7));
      color: hsl(${theme.senderTextColor});
    }

    .message-avatar img {
      width: 100%;
      height: 100%;
      border-radius: 50%;
      object-fit: cover;
    }

    .message-bubble {
      max-width: 75%;
      padding: 10px 16px;
      box-shadow: 0 1px 2px rgba(0,0,0,0.05);
    }

    .message-bubble.contact {
      background: hsl(${theme.receiverBubbleColor});
      color: hsl(${theme.receiverTextColor});
      border-top-left-radius: ${theme.receiverBorderRadius?.topLeft ?? 4}px;
      border-top-right-radius: ${theme.receiverBorderRadius?.topRight ?? 16}px;
      border-bottom-right-radius: ${theme.receiverBorderRadius?.bottomRight ?? 16}px;
      border-bottom-left-radius: ${theme.receiverBorderRadius?.bottomLeft ?? 16}px;
    }

    .message-bubble.user {
      background: hsl(${theme.senderBubbleColor});
      color: hsl(${theme.senderTextColor});
      border-top-left-radius: ${theme.senderBorderRadius?.topLeft ?? 16}px;
      border-top-right-radius: ${theme.senderBorderRadius?.topRight ?? 4}px;
      border-bottom-right-radius: ${theme.senderBorderRadius?.bottomRight ?? 16}px;
      border-bottom-left-radius: ${theme.senderBorderRadius?.bottomLeft ?? 16}px;
    }

    .end-indicator {
      display: flex;
      justify-content: center;
      padding-top: 16px;
    }

    .end-badge {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 8px 16px;
      border-radius: 20px;
      background: rgba(16, 185, 129, 0.15);
      color: #10b981;
      font-size: 14px;
      font-weight: 500;
    }

    .end-badge-dot {
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: #10b981;
    }

    .response-options {
      border-top: 1px solid #e5e7eb;
      padding: 16px;
      background: white;
    }

    .options-label {
      font-size: 11px;
      font-weight: 500;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 12px;
    }

    .options-container {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
    }

    .option-btn {
      padding: 8px 16px;
      border-radius: 12px;
      border: 1px solid #e5e7eb;
      background: white;
      cursor: pointer;
      font-size: 14px;
      transition: all 0.2s;
    }

    .option-btn:hover {
      background: hsl(${theme.senderBubbleColor});
      color: hsl(${theme.senderTextColor});
      border-color: hsl(${theme.senderBubbleColor});
    }

    .option-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .start-screen {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .start-content {
      text-align: center;
      max-width: 280px;
    }

    .start-icon {
      width: 80px;
      height: 80px;
      border-radius: 24px;
      background: #f3f4f6;
      margin: 0 auto 16px;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .start-icon svg {
      width: 40px;
      height: 40px;
      color: #9ca3af;
    }

    .start-title {
      font-size: 18px;
      font-weight: 600;
      color: #1f2937;
      margin-bottom: 8px;
    }

    .start-text {
      font-size: 14px;
      color: #6b7280;
      margin-bottom: 20px;
    }

    .start-btn {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 10px 20px;
      border-radius: 12px;
      border: none;
      background: hsl(${theme.senderBubbleColor});
      color: hsl(${theme.senderTextColor});
      font-size: 14px;
      font-weight: 500;
      cursor: pointer;
      box-shadow: 0 4px 12px hsl(${theme.senderBubbleColor} / 0.25);
      transition: all 0.2s;
    }

    .start-btn:hover {
      transform: translateY(-1px);
      box-shadow: 0 6px 16px hsl(${theme.senderBubbleColor} / 0.3);
    }

    .start-btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
      transform: none;
    }
  </style>
</head>
<body>
  <div class="chat-container" id="app"></div>

  <script>
    (function() {
      const scenario = ${scenarioJSON};
      const { messages, variables, rootMessageId, theme } = scenario;

      let chatHistory = [];
      let currentMessageId = null;
      let isPlaying = false;
      let variableState = {};

      // Initialize variable state from defaults
      Object.values(variables || {}).forEach(v => {
        variableState[v.id] = v.defaultValue;
      });

      function getInitials(name) {
        return name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2);
      }

      function checkCondition(condition) {
        if (!condition) return true;
        return variableState[condition.variableId] === condition.requiredValue;
      }

      function applyVariableAssignment(assignment) {
        if (assignment) {
          variableState[assignment.variableId] = assignment.value;
        }
      }

      function getVisibleOptions(message) {
        if (!message || !message.responseOptions) return [];
        return message.responseOptions.filter(opt => checkCondition(opt.condition));
      }

      function render() {
        const app = document.getElementById('app');
        const currentMessage = currentMessageId ? messages[currentMessageId] : null;
        const rootMessage = rootMessageId ? messages[rootMessageId] : null;

        const visibleOptions = getVisibleOptions(currentMessage);
        const isEnded = isPlaying && currentMessage && 
          (currentMessage.isEndpoint || visibleOptions.length === 0);
        const isDeadEnd = isPlaying && !currentMessageId && chatHistory.length > 0;

        let html = '';

        // Header
        html += '<div class="chat-header">';
        html += '<div class="avatar">';
        if (theme.contactAvatar) {
          html += '<img src="' + theme.contactAvatar + '" alt="' + theme.contactName + '">';
        } else {
          html += getInitials(theme.contactName);
        }
        html += '</div>';
        html += '<div class="header-info">';
        html += '<div class="header-name">' + theme.contactName + '</div>';
        html += '<div class="header-status">';
        html += '<span class="status-dot"></span>';
        html += isPlaying ? 'Active now' : 'Click Start to begin';
        html += '</div></div>';
        if (isPlaying) {
          html += '<button class="reset-btn" onclick="handleReset()">↻ Reset</button>';
        }
        html += '</div>';

        if (!isPlaying) {
          // Start screen
          html += '<div class="start-screen"><div class="start-content">';
          html += '<div class="start-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg></div>';
          html += '<div class="start-title">' + (rootMessage ? 'Ready to Start' : 'No Messages') + '</div>';
          html += '<div class="start-text">' + (rootMessage ? 'Begin the conversation' : 'This scenario has no messages') + '</div>';
          html += '<button class="start-btn" onclick="handleStart()"' + (!rootMessage ? ' disabled' : '') + '>';
          html += '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>';
          html += 'Start';
          html += '</button></div></div>';
        } else {
          // Messages
          html += '<div class="chat-messages">';
          chatHistory.forEach(bubble => {
            html += '<div class="message-row ' + (bubble.isUser ? 'user' : 'contact') + '">';
            if (!bubble.isUser) {
              html += '<div class="message-avatar">';
              if (theme.contactAvatar) {
                html += '<img src="' + theme.contactAvatar + '" alt="' + theme.contactName + '">';
              } else {
                html += getInitials(theme.contactName);
              }
              html += '</div>';
            }
            html += '<div class="message-bubble ' + (bubble.isUser ? 'user' : 'contact') + '">';
            html += bubble.content || '<em style="opacity:0.6">Empty message</em>';
            html += '</div></div>';
          });

          if (isEnded || isDeadEnd) {
            html += '<div class="end-indicator"><span class="end-badge">';
            html += '<span class="end-badge-dot"></span>';
            html += isEnded ? 'Conversation Complete' : 'End of Branch';
            html += '</span></div>';
          }
          html += '</div>';

          // Response options
          if (currentMessage && !currentMessage.isEndpoint && visibleOptions.length > 0) {
            html += '<div class="response-options">';
            html += '<div class="options-label">Choose a response</div>';
            html += '<div class="options-container">';
            visibleOptions.forEach(opt => {
              html += '<button class="option-btn" onclick="handleSelect(\\'' + opt.id + '\\')"' + (!opt.text ? ' disabled' : '') + '>';
              html += opt.text || 'Empty option';
              html += '</button>';
            });
            html += '</div></div>';
          }
        }

        app.innerHTML = html;
      }

      window.handleStart = function() {
        if (!rootMessageId || !messages[rootMessageId]) return;
        
        // Reset variable state
        Object.values(variables || {}).forEach(v => {
          variableState[v.id] = v.defaultValue;
        });

        isPlaying = true;
        chatHistory = [{
          id: rootMessageId,
          content: messages[rootMessageId].content,
          isUser: false
        }];
        currentMessageId = rootMessageId;
        render();
      };

      window.handleReset = function() {
        isPlaying = false;
        chatHistory = [];
        currentMessageId = null;
        
        // Reset variable state
        Object.values(variables || {}).forEach(v => {
          variableState[v.id] = v.defaultValue;
        });
        
        render();
      };

      window.handleSelect = function(optionId) {
        const currentMessage = messages[currentMessageId];
        if (!currentMessage) return;

        const option = currentMessage.responseOptions.find(o => o.id === optionId);
        if (!option) return;

        // Apply variable assignment
        applyVariableAssignment(option.setsVariable);

        // Add user response
        chatHistory.push({
          id: 'user-' + optionId,
          content: option.text,
          isUser: true
        });

        // Add next message if exists
        if (option.nextMessageId && messages[option.nextMessageId]) {
          const nextMsg = messages[option.nextMessageId];
          // Check if next message meets its condition
          if (checkCondition(nextMsg.condition)) {
            chatHistory.push({
              id: option.nextMessageId,
              content: nextMsg.content,
              isUser: false
            });
            currentMessageId = option.nextMessageId;
          } else {
            currentMessageId = null;
          }
        } else {
          currentMessageId = null;
        }

        render();
      };

      render();
    })();
  </script>
</body>
</html>`;
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
